# .github/workflows/deploy_backend.yml
name: Build and deploy FastAPI backend to Azure App Service - up2d8

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: up2d8
  PYTHON_VERSION: '3.12'
  WORKING_DIRECTORY: backend

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_55E9F9E363FD404D9D429EBC3DC7291A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F012F5B2F6F94CB0A6330C61E57AEFC2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8AF832FC630D41608A87BC78F441C334 }}

      - name: Get Resource Group Name
        id: get_rg
        run: |
          RG_NAME=$(az webapp show --name ${{ env.AZURE_WEBAPP_NAME }} --query resourceGroup -o tsv)
          echo "rg_name=$RG_NAME" >> $GITHUB_OUTPUT
          echo "Resource Group: $RG_NAME"

      - name: Stop Azure Web App
        run: az webapp stop --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group ${{ steps.get_rg.outputs.rg_name }}

      - name: Start Azure Web App
        run: az webapp start --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group ${{ steps.get_rg.outputs.rg_name }}

      - name: Deploy to Azure Web App using Oryx build
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.WORKING_DIRECTORY }}
