# .github/workflows/deploy_backend.yml
name: Build and deploy FastAPI backend to Azure App Service - up2d8

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: up2d8
  PYTHON_VERSION: '3.12'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare Azure deployment (use lightweight requirements)
        run: |
          cd backend
          mv requirements.txt requirements-dev.txt
          mv requirements-azure.txt requirements.txt

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_55E9F9E363FD404D9D429EBC3DC7291A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F012F5B2F6F94CB0A6330C61E57AEFC2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8AF832FC630D41608A87BC78F441C334 }}

      - name: Deploy to Azure Web App with Oryx build
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ./backend
          # Let Oryx build the app automatically
